#!/bin/sh
set -eu

# Render the source-address -> device-name mapping from SYSLOG_DEVICES, then
# start rsyslog. Same pattern as prometheus-docker's entrypoints: addresses
# live in .env, never in a committed file.
#
# SYSLOG_DEVICES is a space-separated list of "address|name", e.g.
#   SYSLOG_DEVICES="192.0.2.1|edge-firewall 192.0.2.2|switch-01"

DEVICES_FILE=/etc/rsyslog.d/10-devices.conf
UNKNOWN_DEVICE="${SYSLOG_UNKNOWN_DEVICE:-_unknown}"

mkdir -p /etc/rsyslog.d /var/spool/rsyslog /var/log/network

{
  echo '# Generated by entrypoint.sh from SYSLOG_DEVICES - do not edit.'
  echo 'ruleset(name="resolveDevice") {'
  # Anything that does not match a known sender is filed under _unknown rather
  # than dropped: during bring-up a silent drop is indistinguishable from "not
  # receiving at all". Retention covers that directory too. To drop instead,
  # replace the default below with `stop`.
  printf '  set $.device = "%s";\n' "${UNKNOWN_DEVICE}"

  for entry in ${SYSLOG_DEVICES:-}; do
    name="${entry#*|}"
    addr="${entry%%|*}"
    if [ "${name}" = "${entry}" ] || [ -z "${addr}" ]; then
      echo "rsyslog-entrypoint: skipping malformed SYSLOG_DEVICES entry '${entry}'" >&2
      continue
    fi
    printf '  if $fromhost-ip == "%s" then { set $.device = "%s"; }\n' "${addr}" "${name}"
  done

  echo '}'
} > "${DEVICES_FILE}"

echo "rsyslog-entrypoint: device map:" >&2
sed 's/^/  /' "${DEVICES_FILE}" >&2

# Fail fast on a bad config rather than restart-looping with no explanation.
rsyslogd -N1 -f /etc/rsyslog.conf

exec rsyslogd -n -f /etc/rsyslog.conf "$@"
